export default [
  { id: "1", imageName: "video1.mp4", tag: "new" },
  // { id: "2", imageName: "gallery1.jpeg", tag: "free" },
  { id: "2", imageName: "gallery2.jpeg", tag: "new" },
  { id: "3", imageName: "gallery3.png", tag: "pro" },
  { id: "4", imageName: "gallery4.png", tag: "pro" },
  { id: "5", imageName: "gallery5.png", tag: "free" },
  { id: "6", imageName: "gallery6.png", tag: "new" },
  // { id: "7", imageName: "gallery7.png", tag: "pro" },
  // { id: "8", imageName: "08.jpeg", tag: "free" },
  // { id: "9", imageName: "09.jpeg", tag: "new" },
  // { id: "10", imageName: "10.jpeg", tag: "new" },
  // { id: "11", imageName: "11.jpeg", tag: "new" },
  // { id: "12", imageName: "12.jpeg", tag: "new" },
  // { id: "13", imageName: "13.jpeg", tag: "free" },
  // { id: "14", imageName: "14.jpeg", tag: "pro" },
  // { id: "15", imageName: "15.jpeg", tag: "free" },
  // { id: "16", imageName: "16.jpeg", tag: "new" },
];
